### ISSUE TITLE
Minor bugfixes

### ISSUE THREAD

**Issue by Thefantasticbagle** [AxelJacobsen/FolkHorror#122]

**Comment by Thefantasticbagle** [comment]
* Buggy wall hitboxes, allowing the player to exit the map.
* Healthbar might be a bit too large.
* AIs could need a little bit of randomness.

**Comment by Thefantasticbagle** [comment]
* Player healthbar is visible through walls

**Comment by Thefantasticbagle** [comment]
* Bleeding/Burning enemies spam sound effects, clogging the system

**Comment by Thefantasticbagle** [comment]
* Add ability to aim with controller scheme

**Comment by AxelJacobsen** [comment]
You cant die twice
